export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';
export const ADD_QUERYPRODUCTS = 'ADD_QUERYPRODUCTS';
export const QUERYPRODUCTS_LOADING = 'QUERYPRODUCTS_LOADING';
export const QUERYPRODUCTS_FAILED = 'QUERYPRODUCTS_FAILED';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const SELLER_LOGIN_REQUEST = 'SELLER_LOGIN_REQUEST';
export const SELLER_LOGIN_SUCCESS = 'SELLER_LOGIN_SUCCESS';
export const SELLER_LOGIN_FAILURE = 'SELLER_LOGIN_FAILURE';
export const SELLER_LOGOUT_SUCCESS = 'SELLER_LOGOUT_SUCCESS';
export const SELLER_LOGOUT_REQUEST = 'SELLER_LOGOUT_REQUEST';
export const SELLER_SIGNUP_REQUEST = 'SELLER_SIGNUP_REQUEST';
export const SELLER_SIGNUP_SUCCESS = 'SELLER_SIGNUP_SUCCESS';
export const SELLER_SIGNUP_FAILURE = 'SELLER_SIGNUP_FAILURE';


export const SELLER_LOADING = 'SELLER_LOADING';
export const SELLER_FAILED = 'SELLER_FAILED';
export const SELLER_GET = 'SELLER_GET'; 

export const UPDATE_SELLER_LOADING = 'UPDATE_SELLER_LOADING';
export const UPDATE_SELLER_FAILED = 'UPDATE_SELLER_FAILED';
export const UPDATE_SELLER_SUCCESS = 'UPDATE_SELLER_SUCCESS'; 

export const UPDATE_PRODUCT_LOADING = 'UPDATE_PRODUCT_LOADING';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'; 

export const UPDATE_USER_LOADING = 'UPDATE_USER_LOADING';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'; 

export const USER_LOADING = 'USER_LOADING';
export const USER_FAILED = 'USER_FAILED';
export const USER_GET = 'USER_GET'; 

export const UPLOAD_PRODUCTS = 'UPLOAD_PRODUCTS';
export const UPLOAD_PRODUCTS_LOADING = 'UPLOAD_PRODUCTS_LOADING';
export const UPLOAD_PRODUCTS_FAILED = 'UPLOAD_PRODUCTS_FAILED';

export const UPLOAD_PRODUCT_IMAGE = 'UPLOAD_PRODUCT_IMAGE';
export const UPLOAD_PRODUCTS_IMAGE_LOADING = 'UPLOAD_PRODUCTS_IMAGE_LOADING';
export const UPLOAD_PRODUCTS_IMAGE_FAILED = 'UPLOAD_PRODUCTS_IMAGE_FAILED';

